---

# tasks file for pgbouncer
- name: set distro independed variables
  ansible.builtin.include_vars:
    file: "{{ pgbouncer_vars_dir }}/main.yml"
  tags: pgbouncer,pgbouncer_install,pgbouncer_config

- name: install pgbouncer
  ansible.builtin.package:
    name: pgbouncer
    state: present
  tags: pgbouncer,pgbouncer_install

- name: check if config dir exists
  ansible.builtin.file:
    path: "{{ pgbouncer_config_dir }}"
    state: "directory"
    owner: "{{ pgbouncer_system_user }}"
    group: "{{ pgbouncer_system_group }}"
    mode: '0750'
  tags: pgbouncer,pgbouncer_config

- name: configure pgbouncer
  ansible.builtin.template:
    dest: "{{ pgbouncer_config_file }}"
    src: "{{ pgbouncer_templates_dir }}/pgbouncer.ini.j2"
    owner: "{{ pgbouncer_system_user }}"
    group: "{{ pgbouncer_system_group }}"
    mode: '0640'
  notify: pgbouncer reload
  tags: pgbouncer,pgbouncer_config

- name: set HBA if it is defined
  ansible.builtin.template:
    dest: "{{ pgbouncer_auth_hba_file }}"
    src: "{{ pgbouncer_templates_dir }}/pg_hba.conf.j2"
    owner: "{{ pgbouncer_system_user }}"
    group: "{{ pgbouncer_system_group }}"
    mode: '0640'
  when: pgbouncer_auth_hba_file is defined and pgbouncer_auth_hba_file | length > 0
  notify: pgbouncer reload
  tags: pgbouncer,pgbouncer_auth_hba

- name: set user list
  ansible.builtin.template:
    dest: "{{ pgbouncer_user_file }}"
    src: "{{ pgbouncer_templates_dir }}/userlist.txt.j2"
    owner: "{{ pgbouncer_system_user }}"
    group: "{{ pgbouncer_system_group }}"
    mode: '0600'
  notify: pgbouncer reload
  tags: pgbouncer,pgbouncer_user

  
