---

# tasks file for pgbouncer
- name: set distro independed variables
  ansible.builtin.include_vars:
    file: "{{ pgbouncer_vars_dir }}/main.yml"
  tags: pgbouncer,pgbouncer_install,pgbouncer_config

- name: install pgbouncer
  ansible.builtin.package:
    name: pgbouncer
    state: present
  tags: pgbouncer,pgbouncer_install

- name: add databases into pgbouncer
  ansible.builtin.blockinfile:
    path: "{{ pgbouncer_config_file }}"
    insertafter: '^\[databases\]'
    block: |
      {% for db in pgbouncer_databases %}
      {{ db.name }} = {{ db.connstring }}
      {% endfor %}
  notify: pgbouncer restart
  tags: pgbouncer,pgbouncer_config

- name: set pgbouncer parameters
  ansible.builtin.lineinfile:
    path: "{{ pgbouncer_config_file }}"
    regexp: '^;?\s*{{ item.name }}'
    line: '{{ item.name }} = {{ item.value }}'
  loop: "{{ pgbouncer_params }}"
  notify: pgbouncer restart
  tags: pgbouncer,pgbouncer_config

- name: set user list
  ansible.builtin.lineinfile:
    path: "{{ pgbouncer_user_file }}"
    line: '"{{ item.name }}" "{{ item.value }}"'
  loop: "{{ pgbouncer_users }}"
  notify: pgbouncer restart
  tags: pgbouncer,pgbouncer_config,pgbouncer_user
