---
# handlers file for pgbouncer
- name: pgbouncer restart
  ansible.builtin.service:
    name: pgbouncer
    state: restarted

- name: pgbouncer reload
  ansible.builtin.service:
    name: pgbouncer
    state: reloaded
